[build-system]
requires = ['setuptools>=44.0.0', 'wheel']
build-backend = 'setuptools.build_meta'

[project]
name = 'qtoolkit'
version = '0.1.0'
requires-python = '>=3.9'
authors = [
    {name = 'Faris Redza', email = 'faris.redza1999@gmail.com'}
]
maintainers = [
    {name = 'Faris Redza', email = 'faris.redza1999@gmail.com'}
]
readme = 'README.md'
classifiers = [
    'Intended Audience :: Science/Research',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
]

dependencies = [
    'numpy>=2.0.0',
    'numba>=0.60.0'
]
[project.optional-dependencies]
dev = [
    'pytest>=5.1.0',
    'pytest-cov>=7.0.0',
    'vermin>=0.2.2'
]
doc = [
    'sphinx>=7.0.0',
    'piccolo-theme>=0.24.0'
]

[project.urls]
Homepage = 'https://github.com/FarisRedza/qtoolkit'
Repository = 'https://github.com/FarisRedza/qtoolkit.git'

[tool.pytest.ini_options]
addopts = [
    '--cov=qtoolkit',
    '--cov-report=term-missing',
    '--cov-branch'
]
testpaths = [
    'tests',
]